CREATE TABLE IF NOT EXISTS orders(
    id SERIAL PRIMARY KEY,
    num VARCHAR (255) NOT NULL,
    user_id INTEGER REFERENCES users (id),
    status VARCHAR (64) NOT NULL,
    accrual NUMERIC NOT NULL DEFAULT 0,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);