CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    login VARCHAR (128) UNIQUE NOT NULL,
    hash VARCHAR (128) NOT NULL,
    balance NUMERIC NOT NULL DEFAULT 0,
    withdrawn NUMERIC NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS orders(
    id VARCHAR (255) NOT NULL PRIMARY KEY,
    user_id INTEGER REFERENCES users (id),
    status VARCHAR (64) NOT NULL,
    accrual NUMERIC NOT NULL DEFAULT 0,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS transactions(
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id),
    order_id VARCHAR (255) NOT NULL,
    amount NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
